openapi: 3.1.0
info:
  title: 'Amazon Step Functions Executions #X Amz Target=AWSStepFunctions.DescribeStateMachineAlias API'
  description: Amazon Step Functions is a serverless workflow orchestration service that lets you coordinate distributed applications and microservices using visual workflows. This API enables you to create and manage state machines, start and monitor executions, and retrieve execution history.
  version: '2016-11-23'
  contact:
    name: Amazon Web Services
    url: https://aws.amazon.com/contact-us/
  termsOfService: https://aws.amazon.com/service-terms/
servers:
- url: https://states.{region}.amazonaws.com
  description: Amazon Step Functions Regional Endpoint
  variables:
    region:
      default: us-east-1
      description: AWS Region
security:
- sigv4Auth: []
tags:
- name: '#X Amz Target=AWSStepFunctions.DescribeStateMachineAlias'
paths:
  /#X-Amz-Target=AWSStepFunctions.DescribeStateMachineAlias:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: DescribeStateMachineAlias
      description: <p>Returns details about a state machine <a href="https://docs.aws.amazon.com/step-functions/latest/dg/concepts-state-machine-alias.html">alias</a>.</p> <p> <b>Related operations:</b> </p> <ul> <li> <p> <a>CreateStateMachineAlias</a> </p> </li> <li> <p> <a>ListStateMachineAliases</a> </p> </li> <li> <p> <a>UpdateStateMachineAlias</a> </p> </li> <li> <p> <a>DeleteStateMachineAlias</a> </p> </li> </ul>
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DescribeStateMachineAliasOutput'
              examples:
                DescribeStateMachineAlias200Example:
                  summary: Default DescribeStateMachineAlias 200
                  x-microcks-default: true
                  value:
                    stateMachineAliasArn: arn:aws:service:us-east-1:123456789012:resource/example
                    name: MyResource
                    description: example-value
                    routingConfiguration: example-value
                    creationDate: example-value
                    updateDate: example-value
        '480':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
              examples:
                DescribeStateMachineAlias480Example:
                  summary: Default DescribeStateMachineAlias 480
                  x-microcks-default: true
                  value: example-value
        '481':
          description: InvalidArn
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidArn'
              examples:
                DescribeStateMachineAlias481Example:
                  summary: Default DescribeStateMachineAlias 481
                  x-microcks-default: true
                  value: example-value
        '482':
          description: ResourceNotFound
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFound'
              examples:
                DescribeStateMachineAlias482Example:
                  summary: Default DescribeStateMachineAlias 482
                  x-microcks-default: true
                  value: example-value
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DescribeStateMachineAliasInput'
            examples:
              DescribeStateMachineAliasRequestExample:
                summary: Default DescribeStateMachineAlias request
                x-microcks-default: true
                value:
                  stateMachineAliasArn: arn:aws:service:us-east-1:123456789012:resource/example
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - AWSStepFunctions.DescribeStateMachineAlias
      summary: Amazon Describe State Machine Alias
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=AWSStepFunctions.DescribeStateMachineAlias'
components:
  parameters:
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
  schemas:
    Name:
      type: string
      minLength: 1
      maxLength: 80
    ValidationException: {}
    DescribeStateMachineAliasOutput:
      type: object
      properties:
        stateMachineAliasArn:
          allOf:
          - $ref: '#/components/schemas/Arn'
          - description: The Amazon Resource Name (ARN) of the state machine alias.
        name:
          allOf:
          - $ref: '#/components/schemas/Name'
          - description: The name of the state machine alias.
        description:
          allOf:
          - $ref: '#/components/schemas/AliasDescription'
          - description: A description of the alias.
        routingConfiguration:
          allOf:
          - $ref: '#/components/schemas/RoutingConfigurationList'
          - description: The routing configuration of the alias.
        creationDate:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: The date the state machine alias was created.
        updateDate:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: <p>The date the state machine alias was last updated.</p> <p>For a newly created state machine, this is the same as the creation date.</p>
    InvalidArn: {}
    RoutingConfigurationListItem:
      type: object
      required:
      - stateMachineVersionArn
      - weight
      properties:
        stateMachineVersionArn:
          allOf:
          - $ref: '#/components/schemas/Arn'
          - description: <p>The Amazon Resource Name (ARN) that identifies one or two state machine versions defined in the routing configuration.</p> <p>If you specify the ARN of a second version, it must belong to the same state machine as the first version.</p>
        weight:
          allOf:
          - $ref: '#/components/schemas/VersionWeight'
          - description: The percentage of traffic you want to route to the second state machine version. The sum of the weights in the routing configuration must be equal to 100.
      description: Contains details about the routing configuration of a state machine alias. In a routing configuration, you define an array of objects that specify up to two state machine versions. You also specify the percentage of traffic to be routed to each version.
    RoutingConfigurationList:
      type: array
      items:
        $ref: '#/components/schemas/RoutingConfigurationListItem'
      minItems: 1
      maxItems: 2
    AliasDescription:
      type: string
      maxLength: 256
      format: password
    VersionWeight:
      type: integer
      minimum: 0
      maximum: 100
    ResourceNotFound: {}
    Timestamp:
      type: string
      format: date-time
    DescribeStateMachineAliasInput:
      type: object
      required:
      - stateMachineAliasArn
      title: DescribeStateMachineAliasInput
      properties:
        stateMachineAliasArn:
          allOf:
          - $ref: '#/components/schemas/Arn'
          - description: The Amazon Resource Name (ARN) of the state machine alias.
    Arn:
      type: string
      minLength: 1
      maxLength: 256
  securitySchemes:
    sigv4Auth:
      type: apiKey
      name: Authorization
      in: header
      description: AWS Signature Version 4 authentication
externalDocs:
  description: Amazon Step Functions API Reference
  url: https://docs.aws.amazon.com/step-functions/latest/apireference/
